### ISSUE TITLE
Model will conflict

### ISSUE THREAD

**Issue by jorenvh** [appzcoder/laravel-roles#1]
Hi,

Just a tip, Laravel ships allready with a User model. Your model will eventullly conflict with the default one. Instead make a trait and update your docs to tell your users to make the user model use your trait.

Kind regards,
Joren

**Comment by sohelamin** [comment]
Hi @jorenvh ,

Thanks for sharing your idea.
I just did as you said though I had a plan to do another thing with it for a another time but could not wait after you said.

Thanks
Sohel Amin

**Comment by jorenvh** [comment]
Glad I could help. Just thinking but first it was user model but why do you call it rolestrait? It's about uwers? Not that it's wrong but the name says somthing else the. It does.

**Comment by sohelamin** [comment]
Thanks again @jorenvh 
I think it is okay now.
And I'm going to close the issue.

**Comment by BrandonSurowiec** [comment]
I disagree with naming it UsersTrait. That tells me nothing about the trait when I read it on this line.

```
use Authenticatable, CanResetPassword, UserTrait;
```

Having the word _roles_ in there was way better to describe what it did. I personally would name it like this:

```
use Authenticatable, CanResetPassword, HasRoles;
```

**Comment by sohelamin** [comment]
Thanks @BrandonSurowiec for giving such a great idea.
I can understand what you point out about the naming.
I will do a better understandable naming on next release or update.
